def calmenu() : 
    print("╔═════════════════╔══════════════════════╗════════════════╗")
    print("║═════════════════╚═══════CALORIES═══════╝════════════════║")
    print("║         1- Hamburger                                    ║ ")
    print("║         2- 1 Pizza Slice                                ║ ")
    print("║         3- 330ml Coca Cola                              ║ ")                            
    print("║         4- 1 Eti Browni                                 ║ ")
    print("║         5- 1 White Mocha                                ║ ")
    print("║         6- 1 Filter Coffee                              ║ ")
    print("║                                                         ║ ")
    print("╚═════════════════════════════════════════════════════════╝ ")
    choice=input()